[
  {":0:unknown_function Function IEx.dont_display_result/0 does not exist.", :unknown_function},
  {":0:unknown_function Function Tai\.LogEvent\.Atom\.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Tai\.LogEvent\.BitString\.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Tai\.LogEvent\.Float\.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Tai\.LogEvent\.Function\.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Tai\.LogEvent\.Integer\.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Tai\.LogEvent\.List\.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Tai\.LogEvent\.Map\.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Tai\.LogEvent\.PID\.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Tai\.LogEvent\.Port\.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Tai\.LogEvent\.Reference\.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Tai\.LogEvent\.Tuple\.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Tai\.Trading.OrderStore.Action\.Atom\.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Tai\.Trading.OrderStore.Action\.BitString\.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Tai\.Trading.OrderStore.Action\.Float\.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Tai\.Trading.OrderStore.Action\.Function\.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Tai\.Trading.OrderStore.Action\.Integer\.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Tai\.Trading.OrderStore.Action\.List\.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Tai\.Trading.OrderStore.Action\.Map\.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Tai\.Trading.OrderStore.Action\.PID\.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Tai\.Trading.OrderStore.Action\.Port\.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Tai\.Trading.OrderStore.Action\.Reference\.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Tai\.Trading.OrderStore.Action\.Tuple\.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Tai\.VenueAdapters.Bitmex.Stream.ProcessAuth.Message\.Atom\.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Tai\.VenueAdapters.Bitmex.Stream.ProcessAuth.Message\.BitString\.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Tai\.VenueAdapters.Bitmex.Stream.ProcessAuth.Message\.Float\.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Tai\.VenueAdapters.Bitmex.Stream.ProcessAuth.Message\.Function\.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Tai\.VenueAdapters.Bitmex.Stream.ProcessAuth.Message\.Integer\.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Tai\.VenueAdapters.Bitmex.Stream.ProcessAuth.Message\.List\.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Tai\.VenueAdapters.Bitmex.Stream.ProcessAuth.Message\.Map\.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Tai\.VenueAdapters.Bitmex.Stream.ProcessAuth.Message\.PID\.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Tai\.VenueAdapters.Bitmex.Stream.ProcessAuth.Message\.Port\.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Tai\.VenueAdapters.Bitmex.Stream.ProcessAuth.Message\.Reference\.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Tai\.VenueAdapters.Bitmex.Stream.ProcessAuth.Message\.Tuple\.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Tai\.VenueAdapters.Bitmex.Stream.ProcessAuth.SubMessage\.Atom\.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Tai\.VenueAdapters.Bitmex.Stream.ProcessAuth.SubMessage\.BitString\.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Tai\.VenueAdapters.Bitmex.Stream.ProcessAuth.SubMessage\.Float\.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Tai\.VenueAdapters.Bitmex.Stream.ProcessAuth.SubMessage\.Function\.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Tai\.VenueAdapters.Bitmex.Stream.ProcessAuth.SubMessage\.Integer\.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Tai\.VenueAdapters.Bitmex.Stream.ProcessAuth.SubMessage\.List\.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Tai\.VenueAdapters.Bitmex.Stream.ProcessAuth.SubMessage\.Map\.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Tai\.VenueAdapters.Bitmex.Stream.ProcessAuth.SubMessage\.PID\.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Tai\.VenueAdapters.Bitmex.Stream.ProcessAuth.SubMessage\.Port\.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Tai\.VenueAdapters.Bitmex.Stream.ProcessAuth.SubMessage\.Reference\.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Tai\.VenueAdapters.Bitmex.Stream.ProcessAuth.SubMessage\.Tuple\.__impl__/1 does not exist.",
   :unknown_function}
]
