defmodule Tai.ExchangeAdapters.Poloniex.SymbolMappingTest do
  use ExUnit.Case, async: true
  doctest Tai.ExchangeAdapters.Poloniex.SymbolMapping

  alias Tai.ExchangeAdapters.Poloniex.SymbolMapping

  test "to_poloniex returns a valid string for the symbol on Poloniex" do
    assert SymbolMapping.to_poloniex(:amp_btc) == "BTC_AMP"
    assert SymbolMapping.to_poloniex(:ardr_btc) == "BTC_ARDR"
    assert SymbolMapping.to_poloniex(:bch_btc) == "BTC_BCH"
    assert SymbolMapping.to_poloniex(:bcn_btc) == "BTC_BCN"
    assert SymbolMapping.to_poloniex(:bcy_btc) == "BTC_BCY"
    assert SymbolMapping.to_poloniex(:bela_btc) == "BTC_BELA"
    assert SymbolMapping.to_poloniex(:blk_btc) == "BTC_BLK"
    assert SymbolMapping.to_poloniex(:btcd_btc) == "BTC_BTCD"
    assert SymbolMapping.to_poloniex(:btm_btc) == "BTC_BTM"
    assert SymbolMapping.to_poloniex(:bts_btc) == "BTC_BTS"
    assert SymbolMapping.to_poloniex(:burst_btc) == "BTC_BURST"
    assert SymbolMapping.to_poloniex(:clam_btc) == "BTC_CLAM"
    assert SymbolMapping.to_poloniex(:cvc_btc) == "BTC_CVC"
    assert SymbolMapping.to_poloniex(:dash_btc) == "BTC_DASH"
    assert SymbolMapping.to_poloniex(:dcr_btc) == "BTC_DCR"
    assert SymbolMapping.to_poloniex(:dgb_btc) == "BTC_DGB"
    assert SymbolMapping.to_poloniex(:doge_btc) == "BTC_DOGE"
    assert SymbolMapping.to_poloniex(:emc2_btc) == "BTC_EMC2"
    assert SymbolMapping.to_poloniex(:etc_btc) == "BTC_ETC"
    assert SymbolMapping.to_poloniex(:eth_btc) == "BTC_ETH"
    assert SymbolMapping.to_poloniex(:exp_btc) == "BTC_EXP"
    assert SymbolMapping.to_poloniex(:fct_btc) == "BTC_FCT"
    assert SymbolMapping.to_poloniex(:fldc_btc) == "BTC_FLDC"
    assert SymbolMapping.to_poloniex(:flo_btc) == "BTC_FLO"
    assert SymbolMapping.to_poloniex(:game_btc) == "BTC_GAME"
    assert SymbolMapping.to_poloniex(:gas_btc) == "BTC_GAS"
    assert SymbolMapping.to_poloniex(:gno_btc) == "BTC_GNO"
    assert SymbolMapping.to_poloniex(:gnt_btc) == "BTC_GNT"
    assert SymbolMapping.to_poloniex(:grc_btc) == "BTC_GRC"
    assert SymbolMapping.to_poloniex(:huc_btc) == "BTC_HUC"
    assert SymbolMapping.to_poloniex(:lbc_btc) == "BTC_LBC"
    assert SymbolMapping.to_poloniex(:lsk_btc) == "BTC_LSK"
    assert SymbolMapping.to_poloniex(:ltc_btc) == "BTC_LTC"
    assert SymbolMapping.to_poloniex(:maid_btc) == "BTC_MAID"
    assert SymbolMapping.to_poloniex(:nav_btc) == "BTC_NAV"
    assert SymbolMapping.to_poloniex(:neos_btc) == "BTC_NEOS"
    assert SymbolMapping.to_poloniex(:nmc_btc) == "BTC_NMC"
    assert SymbolMapping.to_poloniex(:nxc_btc) == "BTC_NXC"
    assert SymbolMapping.to_poloniex(:nxt_btc) == "BTC_NXT"
    assert SymbolMapping.to_poloniex(:omg_btc) == "BTC_OMG"
    assert SymbolMapping.to_poloniex(:omni_btc) == "BTC_OMNI"
    assert SymbolMapping.to_poloniex(:pasc_btc) == "BTC_PASC"
    assert SymbolMapping.to_poloniex(:pink_btc) == "BTC_PINK"
    assert SymbolMapping.to_poloniex(:pot_btc) == "BTC_POT"
    assert SymbolMapping.to_poloniex(:ppc_btc) == "BTC_PPC"
    assert SymbolMapping.to_poloniex(:rads_btc) == "BTC_RADS"
    assert SymbolMapping.to_poloniex(:rep_btc) == "BTC_REP"
    assert SymbolMapping.to_poloniex(:ric_btc) == "BTC_RIC"
    assert SymbolMapping.to_poloniex(:sbd_btc) == "BTC_SBD"
    assert SymbolMapping.to_poloniex(:sc_btc) == "BTC_SC"
    assert SymbolMapping.to_poloniex(:steem_btc) == "BTC_STEEM"
    assert SymbolMapping.to_poloniex(:storj_btc) == "BTC_STORJ"
    assert SymbolMapping.to_poloniex(:str_btc) == "BTC_STR"
    assert SymbolMapping.to_poloniex(:strat_btc) == "BTC_STRAT"
    assert SymbolMapping.to_poloniex(:sys_btc) == "BTC_SYS"
    assert SymbolMapping.to_poloniex(:via_btc) == "BTC_VIA"
    assert SymbolMapping.to_poloniex(:vrc_btc) == "BTC_VRC"
    assert SymbolMapping.to_poloniex(:vtc_btc) == "BTC_VTC"
    assert SymbolMapping.to_poloniex(:xbc_btc) == "BTC_XBC"
    assert SymbolMapping.to_poloniex(:xcp_btc) == "BTC_XCP"
    assert SymbolMapping.to_poloniex(:xem_btc) == "BTC_XEM"
    assert SymbolMapping.to_poloniex(:xmr_btc) == "BTC_XMR"
    assert SymbolMapping.to_poloniex(:xpm_btc) == "BTC_XPM"
    assert SymbolMapping.to_poloniex(:xrp_btc) == "BTC_XRP"
    assert SymbolMapping.to_poloniex(:xvc_btc) == "BTC_XVC"
    assert SymbolMapping.to_poloniex(:zec_btc) == "BTC_ZEC"
    assert SymbolMapping.to_poloniex(:zrx_btc) == "BTC_ZRX"

    assert SymbolMapping.to_poloniex(:bch_eth) == "ETH_BCH"
    assert SymbolMapping.to_poloniex(:cvc_eth) == "ETH_CVC"
    assert SymbolMapping.to_poloniex(:etc_eth) == "ETH_ETC"
    assert SymbolMapping.to_poloniex(:gas_eth) == "ETH_GAS"
    assert SymbolMapping.to_poloniex(:gno_eth) == "ETH_GNO"
    assert SymbolMapping.to_poloniex(:gnt_eth) == "ETH_GNT"
    assert SymbolMapping.to_poloniex(:lsk_eth) == "ETH_LSK"
    assert SymbolMapping.to_poloniex(:omg_eth) == "ETH_OMG"
    assert SymbolMapping.to_poloniex(:rep_eth) == "ETH_REP"
    assert SymbolMapping.to_poloniex(:steem_eth) == "ETH_STEEM"
    assert SymbolMapping.to_poloniex(:zec_eth) == "ETH_ZEC"
    assert SymbolMapping.to_poloniex(:zrx_eth) == "ETH_ZRX"

    assert SymbolMapping.to_poloniex(:bcn_xmr) == "XMR_BCN"
    assert SymbolMapping.to_poloniex(:blk_xmr) == "XMR_BLK"
    assert SymbolMapping.to_poloniex(:btcd_xmr) == "XMR_BTCD"
    assert SymbolMapping.to_poloniex(:dash_xmr) == "XMR_DASH"
    assert SymbolMapping.to_poloniex(:ltc_xmr) == "XMR_LTC"
    assert SymbolMapping.to_poloniex(:maid_xmr) == "XMR_MAID"
    assert SymbolMapping.to_poloniex(:nxt_xmr) == "XMR_NXT"
    assert SymbolMapping.to_poloniex(:zec_xmr) == "XMR_ZEC"

    assert SymbolMapping.to_poloniex(:bch_usdt) == "USDT_BCH"
    assert SymbolMapping.to_poloniex(:btc_usdt) == "USDT_BTC"
    assert SymbolMapping.to_poloniex(:dash_usdt) == "USDT_DASH"
    assert SymbolMapping.to_poloniex(:etc_usdt) == "USDT_ETC"
    assert SymbolMapping.to_poloniex(:eth_usdt) == "USDT_ETH"
    assert SymbolMapping.to_poloniex(:ltc_usdt) == "USDT_LTC"
    assert SymbolMapping.to_poloniex(:nxt_usdt) == "USDT_NXT"
    assert SymbolMapping.to_poloniex(:rep_usdt) == "USDT_REP"
    assert SymbolMapping.to_poloniex(:str_usdt) == "USDT_STR"
    assert SymbolMapping.to_poloniex(:xmr_usdt) == "USDT_XMR"
    assert SymbolMapping.to_poloniex(:xrp_usdt) == "USDT_XRP"
    assert SymbolMapping.to_poloniex(:zec_usdt) == "USDT_ZEC"
  end

  test "to_poloniex returns an upcase string for unknown symbols" do
    assert SymbolMapping.to_poloniex(:unknown) == "UNKNOWN"
    assert SymbolMapping.to_poloniex("unknown") == "UNKNOWN"
  end

  test "to_tai returns an atom of reversed pair" do
    assert SymbolMapping.to_tai("USDT_BTC") == :btc_usdt
  end
end
