defmodule Tai.ExchangeAdapters.Poloniex.SymbolMapping do
  @moduledoc """
  Mappings between tai symbol format and Poloniex currency pair format
  """

  def to_poloniex(:ampbtc), do: "BTC_AMP"
  def to_poloniex(:ardrbtc), do: "BTC_ARDR"
  def to_poloniex(:bchbtc), do: "BTC_BCH"
  def to_poloniex(:bcnbtc), do: "BTC_BCN"
  def to_poloniex(:bcybtc), do: "BTC_BCY"
  def to_poloniex(:belabtc), do: "BTC_BELA"
  def to_poloniex(:blkbtc), do: "BTC_BLK"
  def to_poloniex(:btcdbtc), do: "BTC_BTCD"
  def to_poloniex(:btmbtc), do: "BTC_BTM"
  def to_poloniex(:btsbtc), do: "BTC_BTS"
  def to_poloniex(:burstbtc), do: "BTC_BURST"
  def to_poloniex(:clambtc), do: "BTC_CLAM"
  def to_poloniex(:cvcbtc), do: "BTC_CVC"
  def to_poloniex(:dashbtc), do: "BTC_DASH"
  def to_poloniex(:dcrbtc), do: "BTC_DCR"
  def to_poloniex(:dgbbtc), do: "BTC_DGB"
  def to_poloniex(:dogebtc), do: "BTC_DOGE"
  def to_poloniex(:emc2btc), do: "BTC_EMC2"
  def to_poloniex(:etcbtc), do: "BTC_ETC"
  def to_poloniex(:ethbtc), do: "BTC_ETH"
  def to_poloniex(:expbtc), do: "BTC_EXP"
  def to_poloniex(:fctbtc), do: "BTC_FCT"
  def to_poloniex(:fldcbtc), do: "BTC_FLDC"
  def to_poloniex(:flobtc), do: "BTC_FLO"
  def to_poloniex(:gamebtc), do: "BTC_GAME"
  def to_poloniex(:gasbtc), do: "BTC_GAS"
  def to_poloniex(:gnobtc), do: "BTC_GNO"
  def to_poloniex(:gntbtc), do: "BTC_GNT"
  def to_poloniex(:grcbtc), do: "BTC_GRC"
  def to_poloniex(:hucbtc), do: "BTC_HUC"
  def to_poloniex(:lbcbtc), do: "BTC_LBC"
  def to_poloniex(:lskbtc), do: "BTC_LSK"
  def to_poloniex(:ltcbtc), do: "BTC_LTC"
  def to_poloniex(:maidbtc), do: "BTC_MAID"
  def to_poloniex(:navbtc), do: "BTC_NAV"
  def to_poloniex(:neosbtc), do: "BTC_NEOS"
  def to_poloniex(:nmcbtc), do: "BTC_NMC"
  def to_poloniex(:nxcbtc), do: "BTC_NXC"
  def to_poloniex(:nxtbtc), do: "BTC_NXT"
  def to_poloniex(:omgbtc), do: "BTC_OMG"
  def to_poloniex(:omnibtc), do: "BTC_OMNI"
  def to_poloniex(:pascbtc), do: "BTC_PASC"
  def to_poloniex(:pinkbtc), do: "BTC_PINK"
  def to_poloniex(:potbtc), do: "BTC_POT"
  def to_poloniex(:ppcbtc), do: "BTC_PPC"
  def to_poloniex(:radsbtc), do: "BTC_RADS"
  def to_poloniex(:repbtc), do: "BTC_REP"
  def to_poloniex(:ricbtc), do: "BTC_RIC"
  def to_poloniex(:sbdbtc), do: "BTC_SBD"
  def to_poloniex(:scbtc), do: "BTC_SC"
  def to_poloniex(:steembtc), do: "BTC_STEEM"
  def to_poloniex(:storjbtc), do: "BTC_STORJ"
  def to_poloniex(:strbtc), do: "BTC_STR"
  def to_poloniex(:stratbtc), do: "BTC_STRAT"
  def to_poloniex(:sysbtc), do: "BTC_SYS"
  def to_poloniex(:viabtc), do: "BTC_VIA"
  def to_poloniex(:vrcbtc), do: "BTC_VRC"
  def to_poloniex(:vtcbtc), do: "BTC_VTC"
  def to_poloniex(:xbcbtc), do: "BTC_XBC"
  def to_poloniex(:xcpbtc), do: "BTC_XCP"
  def to_poloniex(:xembtc), do: "BTC_XEM"
  def to_poloniex(:xmrbtc), do: "BTC_XMR"
  def to_poloniex(:xpmbtc), do: "BTC_XPM"
  def to_poloniex(:xrpbtc), do: "BTC_XRP"
  def to_poloniex(:xvcbtc), do: "BTC_XVC"
  def to_poloniex(:zecbtc), do: "BTC_ZEC"
  def to_poloniex(:zrxbtc), do: "BTC_ZRX"

  def to_poloniex(:bcheth), do: "ETH_BCH"
  def to_poloniex(:cvceth), do: "ETH_CVC"
  def to_poloniex(:etceth), do: "ETH_ETC"
  def to_poloniex(:gaseth), do: "ETH_GAS"
  def to_poloniex(:gnoeth), do: "ETH_GNO"
  def to_poloniex(:gnteth), do: "ETH_GNT"
  def to_poloniex(:lsketh), do: "ETH_LSK"
  def to_poloniex(:omgeth), do: "ETH_OMG"
  def to_poloniex(:repeth), do: "ETH_REP"
  def to_poloniex(:steemeth), do: "ETH_STEEM"
  def to_poloniex(:zeceth), do: "ETH_ZEC"
  def to_poloniex(:zrxeth), do: "ETH_ZRX"

  def to_poloniex(:bcnxmr), do: "XMR_BCN"
  def to_poloniex(:blkxmr), do: "XMR_BLK"
  def to_poloniex(:btcdxmr), do: "XMR_BTCD"
  def to_poloniex(:dashxmr), do: "XMR_DASH"
  def to_poloniex(:ltcxmr), do: "XMR_LTC"
  def to_poloniex(:maidxmr), do: "XMR_MAID"
  def to_poloniex(:nxtxmr), do: "XMR_NXT"
  def to_poloniex(:zecxmr), do: "XMR_ZEC"

  def to_poloniex(:bchusdt), do: "USDT_BCH"
  def to_poloniex(:btcusdt), do: "USDT_BTC"
  def to_poloniex(:dashusdt), do: "USDT_DASH"
  def to_poloniex(:etcusdt), do: "USDT_ETC"
  def to_poloniex(:ethusdt), do: "USDT_ETH"
  def to_poloniex(:ltcusdt), do: "USDT_LTC"
  def to_poloniex(:nxtusdt), do: "USDT_NXT"
  def to_poloniex(:repusdt), do: "USDT_REP"
  def to_poloniex(:strusdt), do: "USDT_STR"
  def to_poloniex(:xmrusdt), do: "USDT_XMR"
  def to_poloniex(:xrpusdt), do: "USDT_XRP"
  def to_poloniex(:zecusdt), do: "USDT_ZEC"

  def to_poloniex(symbol) when is_atom(symbol), do: symbol |> Atom.to_string() |> String.upcase()
  def to_poloniex(symbol), do: symbol |> String.upcase()

  def to_tai(currency_pair) do
    currency_pair
    |> String.split("_")
    |> Enum.reverse()
    |> Enum.join("")
    |> String.downcase()
    |> String.to_atom()
  end
end
